env:
  es6: true
  node: true
  mocha: true
extends:
  - standard
  # - plugin:mocha/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - "@typescript-eslint"
  - mocha
ignorePatterns:
  - "*.d.ts"
rules:
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-explicit-any": 1
  "@typescript-eslint/no-unused-vars": warn
  "camelcase": "off"
  "@typescript-eslint/camelcase": "off"
